module.exports = {
    autotask: {
        name: 'autotask',
        description: 'Gestisce tutte le automazioni del server'
    },
    config: {
        name: 'config',
        description: 'Modifica delle impostazioni del bot per questo server',
        welcome_name: 'benvenuto',
        welcome_description: 'Configura il messaggio di benvenuto del server',
        welcome_get_name: 'recuperare',
        welcome_get_description: 'Si dà la configurazione di benvenuto corrente con un esempio',
        welcome_set_name: 'definire',
        welcome_set_description: 'Cambia un valore o più valori di benvenuto',
        welcome_set_channel_name: 'channel',
        welcome_set_channel_description: 'Cambia il salotto di benvenuto',
        welcome_set_background_name: 'fondo',
        welcome_set_background_description: 'L\'immagine di sfondo di benvenuto',
        welcome_set_enabled_name: 'attivato',
        welcome_set_enabled_description: 'Il modulo di benvenuto è attivato?',
        welcome_set_img_enabled_name: 'immagine_attiva',
        welcome_set_img_enabled_description: 'Viene inviata un\'immagine di benvenuto?',
        welcome_set_msg_name: 'definire_msg',
        welcome_set_msg_description: 'Cambia il messaggio di benvenuto',
        autorole_name: 'roleauto',
        autorole_description: 'Ajoutez des roles qui sont donnés au nouveaux membres',
        autorole_action_name: 'action',
        autorole_action_description: 'Selectionnez quelque chose a faire avec les roles automatiques',
        autorole_action_add: 'Ajouter',
        autorole_action_remove: 'Supprimer'
    },
    credits: {
        name: 'credito',
        description: 'Ti dà i crediti di AutoTask'
    },
    giveaway: {
        name: 'concorso',
        description: 'Gestisci i giveaway del server con tutti i comandi secondari !',
        create_name: 'creare',
        create_description: 'Crea un concorso con tante opzioni !',
        create_prize_name: 'prezzo',
        create_prize_description: 'Il premio del/dei vincitori(i)',
        create_winners_name: 'vincitori',
        create_winners_description: 'Il numero di vincitori per questo concorso',
        create_time_name: 'tempo',
        create_time_description: 'Il tempo in minuti del concorso',
        create_channel_name: 'channel',
        create_channel_description: 'Il salone del concorso (non specificato = in questo salone)',
        create_host_name: 'organizzatore',
        create_host_description: 'Chi organizza questo concorso? (non specificato = voi)',
        create_ping_name: 'menzione',
        create_ping_description: 'Il ruolo che sarà menzionato quando il concorso inizia',
        create_required_roles_name: 'ruoli_richiesti',
        create_required_roles_description: 'Elenca tutti i ruoli richiesti per entrare nel concorso (@ruolo1 @ruolo2...)',
        create_bonus_roles_name: 'ruolo_bonus',
        create_bonus_roles_description: 'Elenca tutti i ruoli che danno voci bonus (@ruoli1 2 @ruoli2 1...)',
        create_multiple_win_name: 'vittoria_multipla',
        create_multiple_win_description: 'Una persona può vincere più volte (con le voci bonus) (per impostazione predefinita = non)',
        list_name: 'lista',
        list_description: 'Tu dai tutti i concorso del server',
        list_channel_name: 'channel',
        list_channel_description: 'Il salone in cui i concorso devono essere',
        list_host_name: 'organizzatore',
        list_host_description: 'Chi ha organizzato i concorso ricercati',
        end_name: 'fine',
        end_description: 'Ferma un concorso in corso con o senza vincitori',
        end_message_id_name: 'id_messaggio',
        end_message_id_description: 'L\'identificativo del messaggio del concorso',
        end_winners_name: 'vincitori',
        end_winners_description: 'scegliere il(i) vincitore(i) ?'
    },
    modals: {
        name: 'moduli',
        description: 'Tutti gli ordini con i moduli',
        create_name: 'creare',
        create_description: 'Crea una nuova maschera con un nome univoco',
        create_name_name: 'nome',
        create_name_description: 'Il nome del modulo che deve essere univoco',
        create_channel_name: 'channel',
        create_channel_description: 'Il salotto in cui verranno inviate le risposte',
        delete_name: 'elimina',
        delete_description: 'Elimina uno dei tuoi moduli',
        delete_name_name: 'nome',
        delete_name_descritpion: 'Il nome del modulo da eliminare',
        list_name: 'lista',
        list_description: 'Fornisci tutti i moduli di questo server',
        info_name: 'info',
        info_description: 'Fornisci tutti i campi di uno dei moduli',
        info_name_name: 'nome',
        info_name_description: 'Il nome del modulo',
        send_name: 'inviare',
        send_description: 'Invia un messaggio con un pulsante che apre il modulo',
        send_name_name: 'nome',
        send_name_description: 'Il nome del modulo',
        send_message_name: 'messaggio',
        send_message_description: 'Il messaggio da inviare',
        edit_name: 'modificare',
        edit_description: 'Modificare uno dei moduli',
        edit_name_name: 'nome',
        edit_name_description: 'Cambiare il nome di un modulo',
        edit_name_name_name: 'nome',
        edit_name_name_description: 'Ml nome del modulo',
        edit_name_newname_name: 'nuovo_nome',
        edit_name_newname_description: 'Il nuovo nome del modulo',
        edit_field_remove_name: 'elimina-campo',
        edit_field_remove_description: 'Elimina un campo da un modulo',
        edit_field_remove_name_name: 'nome',
        edit_field_remove_name_description: 'Il nome del modulo',
        edit_field_remove_number_name: 'numero',
        edit_field_remove_number_description: 'Il numero del campo da eliminare (vedi /modal info)',
        edit_field_add_name: 'aggiungere-campo',
        edit_field_add_description: 'Aggiunge un campo a un modulo',
        edit_field_add_name_name: 'nome',
        edit_field_add_name_description: 'Il nome del modulo',
        edit_field_add_fname_name: 'nome_campo',
        edit_field_add_fname_description: 'Il nome del nuovo campo',
        edit_field_add_type_name: 'tipo',
        edit_field_add_type_description: 'Il tipo del campo',
        edit_field_add_type_choice_short: 'Corto',
        edit_field_add_type_choice_long: 'Lungo',
        edit_field_add_required_name: 'Obbligatorio',
        edit_field_add_required_description: 'Questo campo è richiesto?',
        edit_field_add_placeholder_name: 'placeholder',
        edit_field_add_placeholder_description: 'Un piccolo testo di informazioni',
        edit_field_add_min_name: 'min',
        edit_field_add_min_description: 'Il numero minimo di caratteri',
        edit_field_add_max_name: 'max',
        edit_field_add_max_description: 'Il numero massimo di caratteri'
    },
    tickets: {
        name: 'tickets',
        description: 'Tutti gli ordini con i salon di assistenza (tickets)',
        create_name: 'creare',
        create_description: 'Creare Ticket',
        create_name_name: 'nome',
        create_name_description: 'Nome del salon di assistenza (ticket)',
        create_description_name: 'descrizione',
        create_description_description: 'La descrizione del salon di assistenza (ticket)',
        create_category_name: 'categoria',
        create_category_description: 'La categoria in cui verrà creato il salon di assistenza (ticket)'
    },
    help: {
        name: 'aide',
        description: 'Pour avoir de l\'aide pour toutes les commandes et plus.'
    },
    counter: {
        name: 'compteur',
        description: 'Gère les compteurs du serveur',
        get_name: 'récupérer',
        get_description: 'Récupère tous les compteurs du serveur',
        create_name: 'créer',
        create_description: 'Créer un nouveau compteur dans le serveur',
        create_channel_name: 'salon',
        create_channel_description: 'Le salon du compteur',
        create_format_name: 'format',
        create_format_description: '({count} est la variable) Le format du compteur',
        create_type_name: 'type',
        create_type_description: 'Le type du compteur',
        create_type_choice_member: 'Compteur de membres (utilisateurs + bots)',
        create_type_choice_user: 'Compteur d\'utilisateurs',
        create_type_choice_bot: 'Compteur de bots',
        create_type_choice_channel: 'Compteur de salons',
        create_type_choice_role: 'Compteur de roles',
        remove_name: 'supprimer',
        remove_description: 'Supprime un compteur du serveur',
        remove_channel_name: 'salon',
        remove_channel_description: 'Le salon du compteur a supprimer'
    },
    reactionrole: {
        name: 'reactionrole',
        description: 'Gère des boutons qui une fois cliqué donne un role a l\'utilisateur',
        create_name: 'créer',
        create_description: 'Gère des boutons qui une fois cliqué donne un role a l\'utilisateur',
        create_message_name: 'message',
        create_message_description: 'Le contenu du message pour le réaction role',
        create_label_name: 'label',
        create_label_description: 'Le texte sur le bouton',
        create_role_name: 'role',
        create_role_description: 'Le role qui est donné/enlevé/basculer',
        create_type_name: 'type',
        create_type_description: 'Le type du réaction role',
        create_type_choice_add: 'Ajouter',
        create_type_choice_remove: 'Enlever',
        create_type_choice_toggle: 'Basculer'
    },
    privateroom: {
        name: 'salonprivé',
        description: 'Créer des salons privés quand quelqu\'un rejoinds un salon vocal !',
        get_name: 'récupérer',
        get_description: 'Vous donne la configuation du privateroom',
        setchannel_name: 'définirsalon',
        setchannel_description: 'Définis le salon des privaterooms',
        setchannel_channel_name: 'salon',
        setchannel_channel_description: 'Le nouveau salon des privaterooms',
        setenabled_name: 'définiractivé',
        setenabled_description: 'Définis si le système est activé ou non',
        setenabled_enabled_name: 'activé',
        setenabled_enabled_description: 'Est-ce que le système des privaterooms est activé ?',
        permanent_name: 'permanent',
        permanent_description: 'Gère les salons permanants',
        permanent_add_name: 'ajouter',
        permanent_add_description: 'Ajoute un salon permanant (pas supprimé quand il est vide)',
        permanent_add_channel_name: 'salon',
        permanent_add_channel_description: 'Le salon a ajouter',
        permanent_remove_name: 'enlever',
        permanent_remove_description: 'Enlever un salon permanant (supprimé quand il est vide)',
        permanent_remove_channel_name: 'salon',
        permanent_remove_channel_description: 'Le salon a retirer',
        permanent_reset_name: 'réinitialiser',
        permanent_reset_description: 'Retire tous les salons permanants du système priateroom',
        permanent_reset_confirmation_name: 'confirmation',
        permanent_reset_confirmation_description: 'Merci de confirmer l\'action.'
    },
    clear: {
        name: 'clear',
        description: 'Supprime un certain nombre de messages dans un salon',
        number_name: 'nombre',
        number_description: 'Le nombre de messages a supprimer'
    },
    get_message_date: { name: 'Récupérer La Date Du Message' },
    end_giveaway: { name: 'Terminer Le Giveaway' },
    user_info: { name: 'Info De L\'Utilisateur' },
    poll: {
        name: 'sondage',
        description: 'Crée des sondages pour poser des questions à votre communauté',
        create_name: 'créer',
        create_description: 'Crée un nouveau sondage sur votre serveur !',
        create_question_name: 'question',
        create_question_description: 'La question a poser. C\'est le titre de l\'embed',
        create_choices_name: 'choix',
        create_choices_description: 'Les choix séparés par "; ". Example: "Un; Deux; Trois".',
        create_results_name: 'resultats',
        create_results_description: 'Affiche les résultats en live sur l\'embed ?',
        create_time_name: 'temps',
        create_time_description: 'Le durée du sondage. Example: "4d5h12m" => d: jours, h: heures, m: minutes. Max 7 jours',
        create_description_name: 'description',
        create_description_description: 'Une description plus détaillé de votre sondage.',
        create_single_name: 'unique',
        create_single_description: 'Autorise les utilisateurs a choisir plus d\'une option',
        create_channel_name: 'salon',
        create_channel_description: 'Le salon du sondage',
        create_req_role_name: 'role_requis',
        create_req_role_description: 'Un rôle requis pour répondre au sondage'
    },
    hangman: {
        name: 'pendu',
        description: 'Joue au jeu du pendu. Propose des lettres et trouve le mot secret !',
        lang_name: 'langue',
        lang_description: 'La langue du mot secret',
        lang_en: 'Anglais',
        lang_fr: 'Français'
    }
};