module.exports = {
    autotask: {
        name: 'автозадача',
        description: 'Обробляє всю автоматизацію сервера'
    },
    config: {
        name: 'конфігурація',
        description: 'Змінює налаштування бота для цього сервера',
        welcome_name: 'привітання',
        welcome_description: 'Налаштовує вітальне повідомлення сервера',
        welcome_get_name: 'отримати',
        welcome_get_description: 'Наводить поточну конфігурацію привітання з прикладом',
        welcome_set_name: 'визначити',
        welcome_set_description: 'Змінює одне або кілька вітальних значень',
        welcome_set_channel_name: 'канал',
        welcome_set_channel_description: 'Змінити канал привітання',
        welcome_set_background_name: 'фон',
        welcome_set_background_description: 'Вітальне фонове зображення',
        welcome_set_enabled_name: 'увімкнено',
        welcome_set_enabled_description: 'Чи увімкнений модуль привітання?',
        welcome_set_img_enabled_name: 'зображення_увімкнено',
        welcome_set_img_enabled_description: 'Чи надіслано вітальне зображення?',
        welcome_set_msg_name: 'визначити_msg',
        welcome_set_msg_description: 'Змінює вітальне повідомлення',
        autorole_name: 'roleauto',
        autorole_description: 'Ajoutez des roles qui sont donnés au nouveaux membres',
        autorole_action_name: 'action',
        autorole_action_description: 'Selectionnez quelque chose a faire avec les roles automatiques',
        autorole_action_add: 'Ajouter',
        autorole_action_remove: 'Supprimer'
    },
    credits: {
        name: 'відомості',
        description: 'Надає відомості щодо AutoTask'
    },
    giveaway: {
        name: 'розіграш',
        description: 'Керує роздачами на сервері за допомогою всіх підкоманд!',
        create_name: 'створити',
        create_description: 'Створює розіграш із багатьма варіантами!',
        create_prize_name: 'приз',
        create_prize_description: 'Приз для переможця(-ів)',
        create_winners_name: 'переможців',
        create_winners_description: 'Кількість переможців поточного розіграшу',
        create_time_name: 'час',
        create_time_description: 'Час розіграшу у хвилинах',
        create_channel_name: 'канал',
        create_channel_description: 'Канал розіграшу (за замовчуванням = цей канал)',
        create_host_name: 'організатор',
        create_host_description: 'Хто організовує цей розіграш? (за замовчуванням = ви)',
        create_ping_name: 'згадування',
        create_ping_description: 'Роль, яку було згадано на момент початку розіграшу',
        create_required_roles_name: 'необхідні_ролі',
        create_required_roles_description: 'Перераховує всі ролі, які потрібні для участі в розіграші (@роль1 @роль2...)',
        create_bonus_roles_name: 'бонусні_ролі',
        create_bonus_roles_description: 'Перераховує всі ролі, які дають бонусні записи (@роль1 2 @роль2 1...)',
        create_multiple_win_name: 'багаторазовий_виграш',
        create_multiple_win_description: 'Чи може людина виграти кілька разів (з бонусними записами) (за замовчуванням = ні)',
        list_name: 'список',
        list_description: 'Надає вам усі розіграші цього сервера',
        list_channel_name: 'канал',
        list_channel_description: 'Канал, де має бути розіграш',
        list_host_name: 'організатор',
        list_host_description: 'Хто організував розіграш',
        end_name: 'зупинити',
        end_description: 'Зупиняє поточну роздачу з переможцями або без них',
        end_message_id_name: 'id_повідомлення',
        end_message_id_description: 'Ідентифікатор повідомлення про роздачу',
        end_winners_name: 'переможці',
        end_winners_description: 'Обирає переможців?'
    },
    modals: {
        name: 'модулі',
        description: 'Всі команди з модулями',
        create_name: 'створити',
        create_description: 'Створює новий модуль з унікальною назвою',
        create_name_name: 'назва',
        create_name_description: 'Назва модулю, який має бути унікальним',
        create_channel_name: 'канал',
        create_channel_description: 'Канал, куди надсилатимуться відповіді',
        delete_name: 'видалити',
        delete_description: 'Видаляє один із ваших модулів',
        delete_name_name: 'назва',
        delete_name_descritpion: 'Назва модулю, який потрібно видалити',
        list_name: 'список',
        list_description: 'Надає вам усі модулі цього сервера',
        info_name: 'інформація',
        info_description: 'Надає вам усі поля модулю',
        info_name_name: 'назва',
        info_name_description: 'Назва модулю',
        send_name: 'надіслати',
        send_description: 'Надсилає повідомлення за допомогою кнопки, яка відкриває модуль',
        send_name_name: 'назва',
        send_name_description: 'Назва модулю',
        send_message_name: 'повідомлення',
        send_message_description: 'Повідомлення для надсилання',
        edit_name: 'редагувати',
        edit_description: 'Відредагує один із ваших модулів',
        edit_name_name: 'назва',
        edit_name_description: 'Змінює назву одного модулю',
        edit_name_name_name: 'назва',
        edit_name_name_description: 'Назва модулю',
        edit_name_newname_name: 'нова_назва',
        edit_name_newname_description: 'Нова назва модулю',
        edit_field_remove_name: 'видалити-поле',
        edit_field_remove_description: 'Видаляє поле модулю',
        edit_field_remove_name_name: 'назва',
        edit_field_remove_name_description: 'Назва модулю',
        edit_field_remove_number_name: 'номер',
        edit_field_remove_number_description: 'Номер поля, яке потрібно видалити (див. /modal info)',
        edit_field_add_name: 'додати-поле',
        edit_field_add_description: 'Додає поле до модуля',
        edit_field_add_name_name: 'назва',
        edit_field_add_name_description: 'Назва модуля',
        edit_field_add_fname_name: 'назва_поля',
        edit_field_add_fname_description: 'Назва нового поля',
        edit_field_add_type_name: 'тип',
        edit_field_add_type_description: 'Тип поля',
        edit_field_add_type_choice_short: 'Короткий',
        edit_field_add_type_choice_long: 'Довгий',
        edit_field_add_required_name: 'обов\'язково',
        edit_field_add_required_description: 'Це поле обов\'язкове?',
        edit_field_add_placeholder_name: 'заповнювач',
        edit_field_add_placeholder_description: 'Короткий текст інформації',
        edit_field_add_min_name: 'мін',
        edit_field_add_min_description: 'Мінімальна довжина відповіді',
        edit_field_add_max_name: 'макс',
        edit_field_add_max_description: 'Максимальна довжина відповіді'
    },
    tickets: {
        name: 'квитки',
        description: 'Всі команди з квитками',
        create_name: 'створити',
        create_description: 'Створює квиток',
        create_name_name: 'назва',
        create_name_description: 'Назва квитка',
        create_description_name: 'опис',
        create_description_description: 'Опис квитка',
        create_category_name: 'категорія',
        create_category_description: 'Категорія, у якій буде створено квиток'
    },
    help: {
        name: 'довідка',
        description: 'Щоб отримати довідку для всіх команд тощо.'
    },
    counter: {
        name: 'лічильник',
        description: 'Керує лічильниками сервера',
        get_name: 'отримати',
        get_description: 'Отримати всі лічильники сервера',
        create_name: 'створити',
        create_description: 'Створити новий лічильник на цьому сервері',
        create_channel_name: 'канал',
        create_channel_description: 'Канал лічильника',
        create_format_name: 'формат',
        create_format_description: '({count} є змінною) Формат лічильника',
        create_type_name: 'тип',
        create_type_description: 'Тип лічильника',
        create_type_choice_member: 'Кількість учасників (користувачі + боти)',
        create_type_choice_user: 'Кількість користувачів',
        create_type_choice_bot: 'Кількість ботів',
        create_type_choice_channel: 'Кількість каналів',
        create_type_choice_role: 'Кількість роль',
        remove_name: 'видалити',
        remove_description: 'Видалити лічильник сервера',
        remove_channel_name: 'канал',
        remove_channel_description: 'Канал для видалення лічильника'
    },
    reactionrole: {
        name: 'реакційна роль',
        description: 'Керує кнопками, після натискання яких користувач отримує певну роль',
        create_name: 'створити',
        create_description: 'Створює кнопку, яка після натискання надає користувачеві роль',
        create_message_name: 'повідомлення',
        create_message_description: 'Зміст повідомлення для ролі реакції',
        create_label_name: 'текст',
        create_label_description: 'Текст на кнопці',
        create_role_name: 'роль',
        create_role_description: 'Роль, яка надається/вилучається/перемикається',
        create_type_name: 'тип',
        create_type_description: 'Тип ролі реакції',
        create_type_choice_add: 'Додати',
        create_type_choice_remove: 'Видалити',
        create_type_choice_toggle: 'Перемкнути'
    },
    privateroom: {
        name: 'приватна_кімната',
        description: 'Налаштування приватних кімнат під час приєднання до голосового каналу!',
        get_name: 'отримати',
        get_description: 'Дає конфігурацію приватної кімнати',
        setchannel_name: 'встановит_ канал',
        setchannel_description: 'Налаштування каналу приватної кімнати',
        setchannel_channel_name: 'канал',
        setchannel_channel_description: 'Новий приватний канал',
        setenabled_name: 'встановити_увімкн',
        setenabled_description: 'Встановіть, якщо приватні кімнати ввімкнено',
        setenabled_enabled_name: 'включено',
        setenabled_enabled_description: 'Чи ввімкнено систему приватної кімнати?',
        permanent_name: 'постійний',
        permanent_description: 'Керувати постійними каналами для приватних кімнат',
        permanent_add_name: 'додати',
        permanent_add_description: 'Додати постійний канал (не видаляється, якщо він пустий)',
        permanent_add_channel_name: 'канал',
        permanent_add_channel_description: 'Канал, який потрібно додати',
        permanent_remove_name: 'видалити',
        permanent_remove_description: 'Видалити постійний канал (видаляється, коли він пустий)',
        permanent_remove_channel_name: 'канал',
        permanent_remove_channel_description: 'Канал для видалення',
        permanent_reset_name: 'скинути',
        permanent_reset_description: 'Видалити усі постійні канали з приватних кімнат',
        permanent_reset_confirmation_name: 'підтвердження',
        permanent_reset_confirmation_description: 'Будь ласка, підтвердьте це.'
    },
    clear: {
        name: 'clear',
        description: 'Supprime un certain nombre de messages dans un salon',
        number_name: 'nombre',
        number_description: 'Le nombre de messages a supprimer'
    },
    get_message_date: { name: 'Récupérer La Date Du Message' },
    end_giveaway: { name: 'Terminer Le Giveaway' },
    user_info: { name: 'Info De L\'Utilisateur' },
    poll: {
        name: 'sondage',
        description: 'Crée des sondages pour poser des questions à votre communauté',
        create_name: 'créer',
        create_description: 'Crée un nouveau sondage sur votre serveur !',
        create_question_name: 'question',
        create_question_description: 'La question a poser. C\'est le titre de l\'embed',
        create_choices_name: 'choix',
        create_choices_description: 'Les choix séparés par "; ". Example: "Un; Deux; Trois".',
        create_results_name: 'resultats',
        create_results_description: 'Affiche les résultats en live sur l\'embed ?',
        create_time_name: 'temps',
        create_time_description: 'Le durée du sondage. Example: "4d5h12m" => d: jours, h: heures, m: minutes. Max 7 jours',
        create_description_name: 'description',
        create_description_description: 'Une description plus détaillé de votre sondage.',
        create_single_name: 'unique',
        create_single_description: 'Autorise les utilisateurs a choisir plus d\'une option',
        create_channel_name: 'salon',
        create_channel_description: 'Le salon du sondage',
        create_req_role_name: 'role_requis',
        create_req_role_description: 'Un rôle requis pour répondre au sondage'
    },
    hangman: {
        name: 'pendu',
        description: 'Joue au jeu du pendu. Propose des lettres et trouve le mot secret !',
        lang_name: 'langue',
        lang_description: 'La langue du mot secret',
        lang_en: 'Anglais',
        lang_fr: 'Français'
    }
};